baseURL = "https://christopher.sh/"
languageCode = "en-us"
title = "Chris Martin"
favicon = "static/img/favicon.png"

#### THEME  ####

theme = "gallery"

pygmentsStyle            = "monokai"
pygmentsCodefences       = true

# galleryFolder        = "images/"  
clickablePhotos      = true

smallPreviewImages   = false
# smallImagesSubfolder = "small/"

[[params.mainMenu]]
    link = "/portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "/teaching"
    text = "teaching"

[[params.mainMenu]]
    link = "/about"
    text = "about"
